steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: build-gateway
    args: 
      - 'build'
      - '-t'
      - 'us-east1-docker.pkg.dev/${_PROJECT}/mcp-east/gateway:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    id: push-gateway
    args:
      - 'push'
      - 'us-east1-docker.pkg.dev/${_PROJECT}/mcp-east/gateway:latest'
  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-cloudrun
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy gateway \
          --project=${_PROJECT} \
          --region=us-east1 \
          --image=us-east1-docker.pkg.dev/${_PROJECT}/mcp-east/gateway:latest \
          --platform=managed \
          --allow-unauthenticated \
          --port=8000 \
          --set-env-vars=SERVICE_MODE=single,DOC_EV_MODE=safe
substitutions:
  _PROJECT: infinity-x-one-systems
options:
  logging: CLOUD_LOGGING_ONLY
