steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: build-gateway
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/${_PROJECT}/mcp/gateway:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    id: push-gateway
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${_PROJECT}/mcp/gateway:latest'
substitutions:
  _PROJECT: your-gcp-project
  _REGION: us-central1
options:
  logging: CLOUD_LOGGING_ONLY
